### ISSUE TITLE
A Great 'To-Do…'

### ISSUE THREAD

**Issue by RandomDSdevel** [dshadowwolf/ideas-for-a-new-language#3]
@dshadowwolf:  I noticed that you've included a file named `TODO.txt` in this repository's `.gitignore` manifest file.  Any reason you haven't made this public?  Maybe you don't exactly want to use the a plain text file to host these pending tasks of yours?  In that case, have you thought about using GitHub [Projects](https://help.github.com/articles/about-project-boards/) to track at least some of what you have planned for this repository?

**Comment by dshadowwolf** [comment]
a bunch of notes to myself about files I should write and reminders as to the ideas and concepts behind them, public ? Nah 😛

**Comment by RandomDSdevel** [comment]
But people could _help_ you write this stuff up…; oh, well, it's up to you, I guess…  :man_shrugging:
