### ISSUE TITLE
Idea Mining?

### ISSUE THREAD

**Issue by RandomDSdevel** [dshadowwolf/ideas-for-a-new-language#4]
@dshadowwolf:  Would you be OK with me opening a PR committing a list of programming languages I think it might be a good idea to take inspiration from here?

**Comment by dshadowwolf** [comment]
While I've tried to keep free of comparisons-- no, I don't mind. Go for it

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  Um, I was going to have this issue closed with said PR, but whatever…

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  I currently have the composition of the document I've proposed in this issue about half of the way done locally at my current estimate, though that could change, and tentatively plan to finish it, push it to my fork of this repository, and submit it to you in a PR tomorrow.  

P. S. w. r. t. the following quoted context:  

> @dshadowwolf:  Um, I was going to have this issue closed with said PR, but whatever…  

Could you possibly reopen this issue so I can do that, please?

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  Revising my estimate of speculative PR content completion to between some time over this weekend and some time early this coming week.  Hopefully I don't let this slip any further than that…

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  Thanks!  Hopefully I get this done today.

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  Well, _that_ took longer than I predicted.  My apologies for the delay, but #5's ready now!  I hope what's in there actually ends up being useful.

**Comment by RandomDSdevel** [comment]
@dshadowwolf:  Manually closing this since I forgot to put '`Close #4.`' in #5.
